// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProtoTest.proto

package ProtobufTest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage_ItemType int32

const (
	TestMessage_TypeX TestMessage_ItemType = 0
	TestMessage_TypeY TestMessage_ItemType = 1
	TestMessage_TypeZ TestMessage_ItemType = 2
)

var TestMessage_ItemType_name = map[int32]string{
	0: "TypeX",
	1: "TypeY",
	2: "TypeZ",
}

var TestMessage_ItemType_value = map[string]int32{
	"TypeX": 0,
	"TypeY": 1,
	"TypeZ": 2,
}

func (x TestMessage_ItemType) Enum() *TestMessage_ItemType {
	p := new(TestMessage_ItemType)
	*p = x
	return p
}

func (x TestMessage_ItemType) String() string {
	return proto.EnumName(TestMessage_ItemType_name, int32(x))
}

func (x *TestMessage_ItemType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_ItemType_value, data, "TestMessage_ItemType")
	if err != nil {
		return err
	}
	*x = TestMessage_ItemType(value)
	return nil
}

func (TestMessage_ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_71550a4afc3deff8, []int{0, 0}
}

type TestMessage struct {
	ClientName           *string                `protobuf:"bytes,1,req,name=clientName" json:"clientName,omitempty"`
	ClientId             *int32                 `protobuf:"varint,2,req,name=clientId" json:"clientId,omitempty"`
	Description          *string                `protobuf:"bytes,3,opt,name=description,def=NONE" json:"description,omitempty"`
	Messageitems         []*TestMessage_MsgItem `protobuf:"bytes,4,rep,name=messageitems" json:"messageitems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TestMessage) Reset()         { *m = TestMessage{} }
func (m *TestMessage) String() string { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()    {}
func (*TestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_71550a4afc3deff8, []int{0}
}

func (m *TestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage.Unmarshal(m, b)
}
func (m *TestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage.Marshal(b, m, deterministic)
}
func (m *TestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage.Merge(m, src)
}
func (m *TestMessage) XXX_Size() int {
	return xxx_messageInfo_TestMessage.Size(m)
}
func (m *TestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage proto.InternalMessageInfo

const Default_TestMessage_Description string = "NONE"

func (m *TestMessage) GetClientName() string {
	if m != nil && m.ClientName != nil {
		return *m.ClientName
	}
	return ""
}

func (m *TestMessage) GetClientId() int32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *TestMessage) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return Default_TestMessage_Description
}

func (m *TestMessage) GetMessageitems() []*TestMessage_MsgItem {
	if m != nil {
		return m.Messageitems
	}
	return nil
}

type TestMessage_MsgItem struct {
	Id                   *int32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	ItemName             *string               `protobuf:"bytes,2,opt,name=itemName" json:"itemName,omitempty"`
	ItemValue            *int32                `protobuf:"varint,3,opt,name=itemValue" json:"itemValue,omitempty"`
	ItemType             *TestMessage_ItemType `protobuf:"varint,4,opt,name=itemType,enum=ProtobufTest.TestMessage_ItemType" json:"itemType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TestMessage_MsgItem) Reset()         { *m = TestMessage_MsgItem{} }
func (m *TestMessage_MsgItem) String() string { return proto.CompactTextString(m) }
func (*TestMessage_MsgItem) ProtoMessage()    {}
func (*TestMessage_MsgItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_71550a4afc3deff8, []int{0, 0}
}

func (m *TestMessage_MsgItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage_MsgItem.Unmarshal(m, b)
}
func (m *TestMessage_MsgItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage_MsgItem.Marshal(b, m, deterministic)
}
func (m *TestMessage_MsgItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage_MsgItem.Merge(m, src)
}
func (m *TestMessage_MsgItem) XXX_Size() int {
	return xxx_messageInfo_TestMessage_MsgItem.Size(m)
}
func (m *TestMessage_MsgItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage_MsgItem.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage_MsgItem proto.InternalMessageInfo

func (m *TestMessage_MsgItem) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TestMessage_MsgItem) GetItemName() string {
	if m != nil && m.ItemName != nil {
		return *m.ItemName
	}
	return ""
}

func (m *TestMessage_MsgItem) GetItemValue() int32 {
	if m != nil && m.ItemValue != nil {
		return *m.ItemValue
	}
	return 0
}

func (m *TestMessage_MsgItem) GetItemType() TestMessage_ItemType {
	if m != nil && m.ItemType != nil {
		return *m.ItemType
	}
	return TestMessage_TypeX
}

func init() {
	proto.RegisterEnum("ProtobufTest.TestMessage_ItemType", TestMessage_ItemType_name, TestMessage_ItemType_value)
	proto.RegisterType((*TestMessage)(nil), "ProtobufTest.TestMessage")
	proto.RegisterType((*TestMessage_MsgItem)(nil), "ProtobufTest.TestMessage.MsgItem")
}

func init() { proto.RegisterFile("ProtoTest.proto", fileDescriptor_71550a4afc3deff8) }

var fileDescriptor_71550a4afc3deff8 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xb1, 0x9b, 0x88, 0xe6, 0x52, 0x95, 0xc8, 0x93, 0x55, 0x21, 0x64, 0x32, 0x20, 0x4b,
	0x48, 0x19, 0x3a, 0x32, 0xb0, 0x75, 0xc8, 0xd0, 0x80, 0xac, 0x0a, 0x01, 0x5b, 0x68, 0x8e, 0xca,
	0x52, 0xd3, 0x44, 0xb5, 0x3b, 0xf0, 0x39, 0xf8, 0xb8, 0x2c, 0xc8, 0xf9, 0x47, 0x18, 0x3a, 0xf9,
	0xbd, 0x77, 0xf7, 0xe4, 0xdf, 0xc1, 0xd5, 0xf3, 0xb1, 0xb2, 0xd5, 0x06, 0x8d, 0x4d, 0x6a, 0xa7,
	0xd8, 0xac, 0x09, 0x3e, 0x4e, 0x9f, 0x2e, 0x8b, 0x7f, 0x28, 0x84, 0x4e, 0xac, 0xd1, 0x98, 0x7c,
	0x87, 0xec, 0x06, 0x60, 0xbb, 0xd7, 0x78, 0xb0, 0x59, 0x5e, 0x22, 0x27, 0x82, 0xca, 0x40, 0x8d,
	0x12, 0xb6, 0x80, 0x69, 0xeb, 0xd2, 0x82, 0x53, 0x41, 0xa5, 0xaf, 0x06, 0xcf, 0xee, 0x20, 0x2c,
	0xd0, 0x6c, 0x8f, 0xba, 0xb6, 0xba, 0x3a, 0xf0, 0x89, 0x20, 0x32, 0x78, 0xf0, 0xb2, 0xa7, 0x6c,
	0xa5, 0xc6, 0x03, 0xb6, 0x82, 0x59, 0xd9, 0x7e, 0xa7, 0x2d, 0x96, 0x86, 0x7b, 0x62, 0x22, 0xc3,
	0xe5, 0x6d, 0x32, 0x06, 0x4b, 0x46, 0x50, 0xc9, 0xda, 0xec, 0x52, 0x8b, 0xa5, 0xfa, 0x57, 0x5b,
	0x7c, 0x13, 0xb8, 0xec, 0x26, 0x6c, 0x0e, 0x54, 0x17, 0x0d, 0xae, 0xaf, 0xa8, 0x2e, 0x1c, 0xa6,
	0x5b, 0x6a, 0x8e, 0xa0, 0x8e, 0x43, 0x0d, 0x9e, 0x5d, 0x43, 0xe0, 0xf4, 0x4b, 0xbe, 0x3f, 0x61,
	0x03, 0xe9, 0xab, 0xbf, 0x80, 0x3d, 0xb6, 0xcd, 0xcd, 0x57, 0x8d, 0xdc, 0x13, 0x44, 0xce, 0x97,
	0xf1, 0x79, 0xb0, 0xb4, 0xdb, 0x54, 0x43, 0x27, 0xbe, 0x87, 0x69, 0x9f, 0xb2, 0x00, 0x7c, 0xf7,
	0xbe, 0x46, 0x17, 0xbd, 0x7c, 0x8b, 0x48, 0x2f, 0xdf, 0x23, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x5e, 0x4d, 0xec, 0x00, 0x9d, 0x01, 0x00, 0x00,
}
